
language: 'node_js' 
node_js: '8'
cache:
  directories:
    - 'node_modules' 


before_script:
  - npm run lint


deploy:
  provider: pages 
  skip-cleanup: true 
  github-token: $GITHUB_TOKEN 
  local_dir: dist 
  target_branch: master 
  on:
    branch: master 
